// What this site published, enumerated once, for every suite that scans it.
//
// **Why this is a module rather than a function in each test file.** It was a function in each test
// file, and that is precisely how X-64 published an IP address, a `host:port` endpoint and a bearer
// token to a live public site with a fully green gate.
//
// `site.test.mjs` read the built pages with a single non-recursive `readdirSync(dist)`. That was
// total coverage for as long as every page sat at the root of `dist`, which was true from X-63
// until X-64 added `capabilities/`. The moment a page was published one directory down, it fell out
// of *every* content rule at once — no deployment fact, nothing credential-shaped, the base-path
// check, and both of X-77's family-link guards — and nothing anywhere said so, because a scanner
// that scans fewer files does not fail. It reports success faster.
//
// So there is now one enumerator, and the rule it has to satisfy is not "recurse" — recursion is
// just today's fix. It is: **the suite must not be able to silently stop covering pages.** Two
// things enforce that, both in `coverage.test.mjs`:
//
//   `pages()` is measured against the markdown sources VitePress actually publishes, so a page that
//   renders and is not scanned fails the suite rather than passing quietly. A directory added by
//   X-65 is covered the day it is added, by nobody remembering anything; and
//
//   the walker is run against a fixture tree with a page nested two deep, in the convention this
//   repository uses everywhere — `console/test/components.test.mjs`, `check-action-pins.sh`,
//   `codeBlocksOf` — that a scanner which has not just proved it catches a violation is not
//   evidence there are none.

import assert from 'node:assert/strict'
import { readdirSync, readFileSync, existsSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

export const webRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
export const repoRoot = path.resolve(webRoot, '..')
export const dist = path.join(webRoot, '.vitepress', 'dist')

/**
 * Directories that hold no published page, skipped when walking sources.
 *
 * `node_modules` is the one that matters — it is thousands of markdown files, none of them this
 * site's. The others carry no `.md` today and are listed so that adding one there does not silently
 * become a page nobody expected. `README.md` is excluded separately: it is a real file at the root
 * that VitePress is told not to publish, via `srcExclude` in the config.
 */
const NOT_CONTENT = new Set(['node_modules', '.vitepress', 'test', 'scripts', 'public'])

/** Every file under `root` matching `extension`, recursively, as slash-separated relative paths. */
function walk(root, extension, prefix = '') {
  const found = []
  for (const entry of readdirSync(path.join(root, prefix), { withFileTypes: true })) {
    const relative = prefix ? `${prefix}/${entry.name}` : entry.name
    if (entry.isDirectory()) {
      if (prefix === '' && NOT_CONTENT.has(entry.name)) continue
      found.push(...walk(root, extension, relative))
    } else if (entry.name.endsWith(extension)) {
      found.push(relative)
    }
  }
  return found
}

/** The walker, exported so `coverage.test.mjs` can run it against a tree it built on purpose. */
export { walk }

/**
 * Every built page, as `{ name, html }` — `name` relative to `dist`, so a nested page is
 * `capabilities/invoke.html` rather than `invoke.html`.
 *
 * `root` is a parameter because `status.test.mjs` renders hypothetical builds into temporary
 * directories and has to scan those the same way. It defaults to the real output, which is what
 * every caller in `site.test.mjs` wants.
 */
export function pages(root = dist) {
  assert.ok(
    existsSync(root),
    `${root} does not exist — run \`npm run build\` before \`npm test\`; these assertions read the rendered site`
  )
  const names = walk(root, '.html')
  assert.ok(names.length > 0, 'the build produced no HTML pages')
  return names.map((name) => ({ name, html: readFileSync(path.join(root, name), 'utf-8') }))
}

/**
 * Every page VitePress publishes, named as it lands in `dist` — derived from the markdown sources
 * rather than from the output.
 *
 * This is the half that makes coverage checkable. Reading `dist` tells you what the walker found;
 * reading the sources tells you what it *should* have found, and the two disagreeing is the failure
 * that went unnoticed. `404.html` has no source and is not listed: it is generated by the theme.
 */
export function publishedSources() {
  return walk(webRoot, '.md')
    .filter((source) => source !== 'README.md')
    .map((source) => source.replace(/\.md$/, '.html'))
}
